version: "3"
services:
  web-content:
    build:
      dockerfile: Dockerfile-dev
      context: ./web-content
    image: alexsimons/mongo-images-web-content:1.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./web-content:/app
  web-service:
    build: ./web-service
    image: alexsimons/mongo-images-web-service:1.0.0
    ports:
      - "80:80"
  mongo:
    image: mongo:latest
    volumes:
      - "./dataDump/:/data/db"
