version: "3"
services:
  web-content:
    build:
      dockerfile: Dockerfile-dev
      context: ./web-content
    image: alexsimons/web-content
    ports:
      - "3000:3000"
    volumes:
      - ./web-content:/app
  web-service:
    build: ./web-service
    image: alexsimons/web-service
    ports:
      - "8989:8989"
